name: Deploy to Vercel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
      - name: Turbo prune
        run: pnpm dlx turbo prune --scope="apps/web" --scope="apps/api" --out-dir .turbo/pruned
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      - name: Restore turbo cache
        uses: actions/cache@v4
        with:
          path: |
            .turbo
            node_modules/.cache
          key: ${{ runner.os }}-deploy-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-deploy-turbo-
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm test
      - name: Build
        run: pnpm build
      - uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./apps/web
